// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using Google.GData.Client;
using Google.GData.Spreadsheets;


namespace MTUnity.GoogleAPI {
	public class MTSpreadsheet {
		public SpreadsheetEntry sheet;

		private Dictionary<string, MTWorksheet> _worksheets;
		private SpreadsheetsService _service;

		public MTSpreadsheet (SpreadsheetEntry sheet, SpreadsheetsService service) {
			this.sheet = sheet;
			_service = service;
			_worksheets = new Dictionary<string, MTWorksheet>();
		}

		public MTWorksheet GetWorksheet(string name) {
			if (!_worksheets.ContainsKey(name)) { // query for worksheet
				AtomLink link = sheet.Links.FindService (GDataSpreadsheetsNameTable.WorksheetRel, null);
				WorksheetQuery query = new WorksheetQuery(link.HRef.ToString ());
				query.Title = name;
				WorksheetFeed feed = _service.Query (query);
				if (feed.Entries.Count > 0) {
					_worksheets [name] = new MTWorksheet(feed.Entries[0] as WorksheetEntry, _service);
				} else {
					_worksheets [name] = null;
				}
			}
			return _worksheets [name];
		}
	}
}
